<h1>NUMPY</h1>
<p>Numpy is a python library which deals with array data structre.<br>
It is used to create array.<br>
It access and manage arrays.<br>
Arrays are faster than list.<br>
Maintains time complexity using arrays.   </p>

In [1]:
import numpy as np
print("numpy is imported")


numpy is imported


<h1>1. Creating Arrays by using numpy</h1>
<p>Array is a collection of similar elements  and have continous memory allocation.</p>

In [2]:
ls=[45,86,35,98,35,87,44,77,28]

ls

[45, 86, 35, 98, 35, 87, 44, 77, 28]

In [3]:
arr=np.array(ls)
# array using list 
arr

array([45, 86, 35, 98, 35, 87, 44, 77, 28])

In [4]:
type(arr)           # ndarray---> n dimensional array


numpy.ndarray

In [5]:
arr[2]          # time complexity is 1

np.int64(35)

In [6]:
arr.ndim              # returns number of dimensions

1

In [7]:
arr.dtype            #  returns data type

dtype('int64')

In [8]:
ls=[45,86,35,98,35,87,44,77,28,12.54]       # only one item is float  but in output all elements become float
arr=np.array(ls)
arr

array([45.  , 86.  , 35.  , 98.  , 35.  , 87.  , 44.  , 77.  , 28.  ,
       12.54])

In [9]:
arr.dtype

dtype('float64')

In [10]:
ls=[45,86,35,98,35,87,44,77,28, 12.54,"upflairs"]  
arr=np.array(ls)                                      # all elements become string type
arr

array(['45', '86', '35', '98', '35', '87', '44', '77', '28', '12.54',
       'upflairs'], dtype='<U32')

<p> CONTINOUS MEMORY ALLOCATION ---> allocation in continous order , if any cell remain empty previously then it is filled first. </p>

In [11]:
ls=[35,76,34,66,77,65,33,234,98,58,44,25]
arr=np.array(ls)
arr

array([ 35,  76,  34,  66,  77,  65,  33, 234,  98,  58,  44,  25])

In [12]:
arr.mean()            # returns mean of array elements

np.float64(70.41666666666667)

In [13]:
arr.max()              # returns maximum element of array 

np.int64(234)

In [14]:
arr.min()               # returns minimum element of array 

np.int64(25)

In [15]:
arr[2:5:2]              # (start : end : jump)

array([34, 77])

In [16]:
arr+5            # 5 is added to all elements 

array([ 40,  81,  39,  71,  82,  70,  38, 239, 103,  63,  49,  30])

In [17]:
arr.size             # returns total number of elements 

12

In [18]:
len(arr)           # length of array 

12

In [19]:
arr[arr<50]         # elements less than 50

array([35, 34, 33, 44, 25])

In [20]:
arr.shape          # returns number of elements

(12,)

In [21]:
arr2=np.arange(50)     # create 1 D array,   returns 0 to 49 
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [22]:
np.ones(10)          # returns array of 1. of size 10

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
np.ones((10,5))      # create 2D array      rows = 10 , col= 5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

<p> 2D ARRAY= matrix </p>

In [24]:
np.ones((2,3,4))       #create 3D array of ones (table,row,column)

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [25]:
np.zeros(10)                      # returns 1d array of 0. of size 10

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.linspace(1,8,5)          # in btw 1 to 8 print 5 elements

array([1.  , 2.75, 4.5 , 6.25, 8.  ])

<h1>2. Random methods</h1>

In [27]:
import random

In [28]:
random.randint(1,10)    # returns random value btw 1 to 10

5

In [29]:
random.random()          # returns float value in btw 0 to 1

0.6450694921406873

In [30]:
ls=["arushi","nikita", "pragati","yasmeen","princy","kartik","ronak"]
ls

['arushi', 'nikita', 'pragati', 'yasmeen', 'princy', 'kartik', 'ronak']

In [31]:
random.choice(ls)             # returns random element from iterable

'ronak'

In [32]:
random.choices(ls,k=3)         # returns 3 elements randomly from the list

['nikita', 'ronak', 'pragati']

In [33]:
random.shuffle(ls)        # shuffle the elements 
ls

['pragati', 'yasmeen', 'kartik', 'ronak', 'nikita', 'arushi', 'princy']

In [34]:
np.random.randint(1,50,23)

array([48, 35, 10, 30, 26, 19,  6, 24, 10, 40,  2, 13, 34, 39, 31, 48,  5,
        6,  3, 41, 13, 42, 39], dtype=int32)

In [35]:
arr=np.arange(60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

<h1>3. Various method to create 1d array</h1>

In [36]:
arr.reshape(12,5)       # convert the above array in 2 D, 3D ,etc    60=12*5, 20*3,15*4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [37]:
arr3=np.resize(arr,(25,25))           # it adds or remove elements for new array randomly from the old array
arr3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,
         6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
        31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
        11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 

In [38]:
arr3.shape

(25, 25)

In [39]:
arr3.ndim

2

In [40]:
arr3.reshape(625)        # 25*25=625

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45

In [41]:
arr3.ravel()        # convert only in 1 D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45

In [42]:
arr3.flatten()        #same as ravel

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45

In [43]:
arr=np.random.randint(5,50,100)
arr

array([38,  5, 26, 22, 43, 43, 38, 21, 45, 38, 14, 29, 16, 16, 23, 34, 15,
       20, 48, 25, 33, 35, 19, 38, 15, 12,  7, 21, 40, 27, 30, 40, 22, 21,
        6, 47, 25, 34, 43, 10, 19, 16, 47, 25, 38, 15, 31, 28,  9, 28, 41,
       20, 43, 18, 16, 21, 48, 39, 18, 16, 18, 47, 23, 42, 37, 46, 19, 36,
       43, 36, 45, 35, 22, 16, 39, 29,  9, 14, 27, 11, 46, 15, 28, 47, 15,
        5, 40, 21, 28, 22,  8, 48, 46, 49, 24, 24, 22, 48, 48, 34],
      dtype=int32)

In [44]:
arr=np.random.randint(5,50,(2,3))
arr

array([[20, 38,  5],
       [36, 30, 46]], dtype=int32)

In [45]:
arr.T             # transpose of 2d array/ matrix

array([[20, 36],
       [38, 30],
       [ 5, 46]], dtype=int32)

In [46]:
arr=np.random.randint(2,12,(10,5))
arr

array([[ 8,  3,  9,  7,  2],
       [ 6, 10,  6,  4,  6],
       [ 7, 11,  6,  4, 10],
       [ 5,  5,  7, 11,  3],
       [ 5,  6, 11, 10,  7],
       [11, 10,  9, 11,  9],
       [ 2, 10,  9,  8,  3],
       [10,  5,  2, 11, 11],
       [11,  3,  2, 10,  7],
       [10,  4, 10,  3, 11]], dtype=int32)

In [47]:
arr[0]         # 1st row

array([8, 3, 9, 7, 2], dtype=int32)

In [48]:
arr[-1]         # last row

array([10,  4, 10,  3, 11], dtype=int32)

In [49]:
arr[7:]    #last 3 rows

array([[10,  5,  2, 11, 11],
       [11,  3,  2, 10,  7],
       [10,  4, 10,  3, 11]], dtype=int32)

In [50]:
arr[:,:2]      #[0:10,0:2]        [row, column]  

array([[ 8,  3],
       [ 6, 10],
       [ 7, 11],
       [ 5,  5],
       [ 5,  6],
       [11, 10],
       [ 2, 10],
       [10,  5],
       [11,  3],
       [10,  4]], dtype=int32)

In [51]:
arr[3:6,2:5]

array([[ 7, 11,  3],
       [11, 10,  7],
       [ 9, 11,  9]], dtype=int32)

In [52]:
arr[::2,2:]     # start: stop: jump

array([[ 9,  7,  2],
       [ 6,  4, 10],
       [11, 10,  7],
       [ 9,  8,  3],
       [ 2, 10,  7]], dtype=int32)

In [53]:
arr.ravel()

array([ 8,  3,  9,  7,  2,  6, 10,  6,  4,  6,  7, 11,  6,  4, 10,  5,  5,
        7, 11,  3,  5,  6, 11, 10,  7, 11, 10,  9, 11,  9,  2, 10,  9,  8,
        3, 10,  5,  2, 11, 11, 11,  3,  2, 10,  7, 10,  4, 10,  3, 11],
      dtype=int32)

In [54]:
arr.reshape(50,)


array([ 8,  3,  9,  7,  2,  6, 10,  6,  4,  6,  7, 11,  6,  4, 10,  5,  5,
        7, 11,  3,  5,  6, 11, 10,  7, 11, 10,  9, 11,  9,  2, 10,  9,  8,
        3, 10,  5,  2, 11, 11, 11,  3,  2, 10,  7, 10,  4, 10,  3, 11],
      dtype=int32)

In [55]:
arr.resize(50)
arr

array([ 8,  3,  9,  7,  2,  6, 10,  6,  4,  6,  7, 11,  6,  4, 10,  5,  5,
        7, 11,  3,  5,  6, 11, 10,  7, 11, 10,  9, 11,  9,  2, 10,  9,  8,
        3, 10,  5,  2, 11, 11, 11,  3,  2, 10,  7, 10,  4, 10,  3, 11],
      dtype=int32)

In [56]:
arr[0]     # 1st element

np.int32(8)

In [57]:
arr[-1]      # last element

np.int32(11)

In [58]:
arr=np.random.randint(2,50,(5,10,5))   # 5 Table , 10 rows , 5 column
arr

array([[[26, 10, 20, 45,  3],
        [45,  4, 22, 22, 35],
        [25, 38, 26, 19, 48],
        [25, 21,  8,  2,  4],
        [43, 14, 12, 13, 33],
        [38,  4,  6, 41, 49],
        [21, 28, 38, 10, 16],
        [22, 30, 13,  3, 34],
        [33, 22, 39, 33, 17],
        [10, 10, 21,  5, 10]],

       [[23, 41, 12, 15, 36],
        [45, 32, 22, 17, 20],
        [ 4,  7, 30, 23,  3],
        [48, 43, 11, 30, 31],
        [16, 46, 32, 11, 43],
        [25, 21, 27, 46, 39],
        [24, 48, 10, 26, 10],
        [23, 36,  9, 44, 28],
        [42, 39, 10, 20, 12],
        [20, 42, 40,  8, 29]],

       [[27, 37, 16, 44, 20],
        [ 4, 41, 44,  6, 29],
        [18, 14, 46, 39, 29],
        [36, 34, 15,  7, 42],
        [47, 48, 37, 20, 40],
        [31, 27, 10, 21, 45],
        [39, 30, 49, 35, 23],
        [ 2, 32, 15, 20, 15],
        [12, 20,  5, 34, 20],
        [27,  8, 47, 47, 39]],

       [[45,  8, 48, 10,  3],
        [47, 21, 40, 25, 44],
        [28,  3, 37, 31, 40],
    

In [59]:
arr.shape

(5, 10, 5)

In [60]:
arr.ndim

3

In [61]:
arr[0]    # 1st table

array([[26, 10, 20, 45,  3],
       [45,  4, 22, 22, 35],
       [25, 38, 26, 19, 48],
       [25, 21,  8,  2,  4],
       [43, 14, 12, 13, 33],
       [38,  4,  6, 41, 49],
       [21, 28, 38, 10, 16],
       [22, 30, 13,  3, 34],
       [33, 22, 39, 33, 17],
       [10, 10, 21,  5, 10]], dtype=int32)

In [62]:
arr[0,8:,2:]

array([[39, 33, 17],
       [21,  5, 10]], dtype=int32)

In [63]:
arr[:,9:,:]

array([[[10, 10, 21,  5, 10]],

       [[20, 42, 40,  8, 29]],

       [[27,  8, 47, 47, 39]],

       [[10, 18, 41, 30, 22]],

       [[45, 48, 38, 35, 39]]], dtype=int32)

In [64]:
arr[:,-1]

array([[10, 10, 21,  5, 10],
       [20, 42, 40,  8, 29],
       [27,  8, 47, 47, 39],
       [10, 18, 41, 30, 22],
       [45, 48, 38, 35, 39]], dtype=int32)

In [65]:
arr=np.array([7,5,9])
arr

array([7, 5, 9])

In [66]:
arr.max()

np.int64(9)

In [67]:
arr.argmax()     # returns index of maximum element

np.int64(2)

In [68]:
arr.argmin()      # returns index of minimum element

np.int64(1)

In [69]:
arr.sort()        # returns sorted array
arr

array([5, 7, 9])

In [70]:
arr[::-1]          # reverse array 

array([9, 7, 5])

In [71]:
arr.argsort()     # returns original index of elements of sorted array 

array([0, 1, 2])

In [72]:
arr=np.random.randint(2,12,(2,3))
arr

array([[7, 7, 6],
       [9, 5, 3]], dtype=int32)

In [73]:
np.unique(arr)    # returns elements which  occur only once 

array([3, 5, 6, 7, 9], dtype=int32)

In [74]:
arr=np.random.randint(2,50,10)
arr

array([31, 25, 33, 21,  8, 30, 46,  7, 23, 23], dtype=int32)

In [75]:
arr.mean()

np.float64(24.7)

In [76]:
np.median(arr)           # returns median of array elements 

np.float64(24.0)

In [77]:
arr.var()              # returns variance of array elements 

np.float64(120.21000000000004)

In [78]:
arr.std()              # returns standard deviation of array elements 

np.float64(10.964032105024138)

In [79]:
np.sqrt(25)           # returns square root of given element  

np.float64(5.0)